package com.aditya.ping.ui.theme

import androidx.compose.ui.graphics.Color

// Material 3 light tokens (seed: #3B6FE0)
val LightPrimary = Color(0xFF3B6FE0)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDAE2FF)
val LightOnPrimaryContainer = Color(0xFF001847)
val LightSecondary = Color(0xFF565E71)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDAE2F9)
val LightOnSecondaryContainer = Color(0xFF131B2B)
val LightTertiary = Color(0xFF705574)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFFDFBFF)
val LightOnBackground = Color(0xFF1A1B22)
val LightSurface = Color(0xFFFDFBFF)
val LightOnSurface = Color(0xFF1A1B22)
val LightSurfaceVariant = Color(0xFFE1E2EC)
val LightOnSurfaceVariant = Color(0xFF44474F)
val LightOutline = Color(0xFF74777F)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightSurfaceContainer = Color(0xFFEEEFF6)
val LightSurfaceContainerHigh = Color(0xFFE8E9F0)

// Material 3 dark tokens
val DarkPrimary = Color(0xFFAAC7FF)
val DarkOnPrimary = Color(0xFF002F6B)
val DarkPrimaryContainer = Color(0xFF1A4793)
val DarkOnPrimaryContainer = Color(0xFFDAE2FF)
val DarkSecondary = Color(0xFFBEC6DC)
val DarkOnSecondary = Color(0xFF283041)
val DarkSecondaryContainer = Color(0xFF3E4759)
val DarkOnSecondaryContainer = Color(0xFFDAE2F9)
val DarkTertiary = Color(0xFFDBBDD7)
val DarkOnTertiary = Color(0xFF382A3C)
val DarkBackground = Color(0xFF12131A)
val DarkOnBackground = Color(0xFFE3E2EA)
val DarkSurface = Color(0xFF12131A)
val DarkOnSurface = Color(0xFFE3E2EA)
val DarkSurfaceVariant = Color(0xFF44474F)
val DarkOnSurfaceVariant = Color(0xFFC4C6D0)
val DarkOutline = Color(0xFF8E909A)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkSurfaceContainer = Color(0xFF1E1F27)
val DarkSurfaceContainerHigh = Color(0xFF282A32)

// AMOLED overrides — true black for OLED battery saving
val AmoledBackground = Color(0xFF000000)
val AmoledSurface = Color(0xFF000000)
val AmoledSurfaceVariant = Color(0xFF0A0A0A)
val AmoledSurfaceContainer = Color(0xFF111111)
val AmoledSurfaceContainerHigh = Color(0xFF1A1A1A)
