package com.aditya.ping.ui.theme

import androidx.compose.ui.graphics.Color

// Ping color palette — coral primary, teal secondary, amber tertiary
// Forces a consistent brand identity across light/dark/AMOLED themes
// (Dynamic Color is disabled by design — see Theme.kt)

// Light tokens
val LightPrimary = Color(0xFFD8483E)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDAD4)
val LightOnPrimaryContainer = Color(0xFF410002)
val LightSecondary = Color(0xFF006A6E)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFF6FF6FA)
val LightOnSecondaryContainer = Color(0xFF002022)
val LightTertiary = Color(0xFFB45200)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDDB3)
val LightOnTertiaryContainer = Color(0xFF3B1700)
val LightBackground = Color(0xFFFAF8F5)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFAF8F5)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceVariant = Color(0xFFEDE0DC)
val LightOnSurfaceVariant = Color(0xFF45474A)
val LightOutline = Color(0xFF76767A)
val LightOutlineVariant = Color(0xFFD0C5C1)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightSurfaceContainer = Color(0xFFF4F1ED)
val LightSurfaceContainerHigh = Color(0xFFEEEAE5)
val LightSurfaceContainerHighest = Color(0xFFE8E4DF)
val LightInverseSurface = Color(0xFF2F3030)
val LightInverseOnSurface = Color(0xFFF1F0EE)
val LightInversePrimary = Color(0xFFFFB4A8)

// Dark tokens
val DarkPrimary = Color(0xFFFFB4A8)
val DarkOnPrimary = Color(0xFF660005)
val DarkPrimaryContainer = Color(0xFF932220)
val DarkOnPrimaryContainer = Color(0xFFFFDAD4)
val DarkSecondary = Color(0xFF4CD9DE)
val DarkOnSecondary = Color(0xFF00373A)
val DarkSecondaryContainer = Color(0xFF004F53)
val DarkOnSecondaryContainer = Color(0xFF6FF6FA)
val DarkTertiary = Color(0xFFFFB87D)
val DarkOnTertiary = Color(0xFF5B3300)
val DarkTertiaryContainer = Color(0xFF824D00)
val DarkOnTertiaryContainer = Color(0xFFFFDDB3)
val DarkBackground = Color(0xFF141313)
val DarkOnBackground = Color(0xFFE6E2E0)
val DarkSurface = Color(0xFF141313)
val DarkOnSurface = Color(0xFFE6E2E0)
val DarkSurfaceVariant = Color(0xFF45474A)
val DarkOnSurfaceVariant = Color(0xFFCDC4C0)
val DarkOutline = Color(0xFF968F8B)
val DarkOutlineVariant = Color(0xFF45474A)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkSurfaceContainer = Color(0xFF211F1F)
val DarkSurfaceContainerHigh = Color(0xFF2C2A2A)
val DarkSurfaceContainerHighest = Color(0xFF373534)
val DarkInverseSurface = Color(0xFFE6E2E0)
val DarkInverseOnSurface = Color(0xFF2F3030)
val DarkInversePrimary = Color(0xFFD8483E)

// AMOLED overrides — true black for OLED battery saving
val AmoledBackground = Color(0xFF000000)
val AmoledSurface = Color(0xFF000000)
val AmoledSurfaceVariant = Color(0xFF0A0A0A)
val AmoledSurfaceContainer = Color(0xFF111111)
val AmoledSurfaceContainerHigh = Color(0xFF1A1A1A)
val AmoledSurfaceContainerHighest = Color(0xFF222222)

// ── Neutral surface tokens (shared across all accent presets) ──
// These don't change with accent — only with light/dark/AMOLED mode.
val Color_OnPrimary = Color(0xFFFFFFFF)
val Color_OnPrimaryContainer = Color(0xFF002020)
val Color_OnSecondary = Color(0xFFFFFFFF)
val Color_OnSecondaryContainer = Color(0xFF051F1F)
val Color_OnTertiary = Color(0xFFFFFFFF)
val Color_OnTertiaryContainer = Color(0xFF061C2E)

val Color_Error = Color(0xFFBA1A1A)
val Color_OnError = Color(0xFFFFFFFF)
val Color_ErrorContainer = Color(0xFFFFDAD6)
val Color_OnErrorContainer = Color(0xFF410002)

// Light neutral surface tones
val Color_Background = Color(0xFFFAFBFB)
val Color_OnBackground = Color(0xFF191C1C)
val Color_Surface = Color(0xFFFAFBFB)
val Color_OnSurface = Color(0xFF191C1C)
val Color_SurfaceVariant = Color(0xFFDAE5E3)
val Color_OnSurfaceVariant = Color(0xFF3F4948)
val Color_SurfaceContainer = Color(0xFFF4F5F5)
val Color_SurfaceContainerLow = Color(0xFFEEF0F0)
val Color_SurfaceContainerLowest = Color(0xFFFFFFFF)
val Color_SurfaceContainerHigh = Color(0xFFEFF1F1)
val Color_SurfaceContainerHighest = Color(0xFFE9EBEB)
val Color_SurfaceBright = Color(0xFFFAFBFB)
val Color_SurfaceDim = Color(0xFFD5DBDB)

// Dark base
val Color_DarkOnPrimary = Color(0xFF003737)
val Color_DarkOnSecondary = Color(0xFF1B3534)
val Color_DarkOnTertiary = Color(0xFF1C3144)

val Color_DarkError = Color(0xFFFFB4AB)
val Color_DarkOnError = Color(0xFF690005)
val Color_DarkErrorContainer = Color(0xFF93000A)
val Color_DarkOnErrorContainer = Color(0xFFFFDAD6)

val Color_DarkBackground = Color(0xFF0E1514)
val Color_DarkOnBackground = Color(0xFFE2E3E1)
val Color_DarkSurface = Color(0xFF0E1514)
val Color_DarkOnSurface = Color(0xFFE2E3E1)
val Color_DarkSurfaceVariant = Color(0xFF3F4948)
val Color_DarkOnSurfaceVariant = Color(0xFFBEC9C7)
val Color_DarkSurfaceContainer = Color(0xFF1A2120)
val Color_DarkSurfaceContainerLow = Color(0xFF161D1C)
val Color_DarkSurfaceContainerLowest = Color(0xFF090F0F)
val Color_DarkSurfaceContainerHigh = Color(0xFF1E2524)
val Color_DarkSurfaceContainerHighest = Color(0xFF222A29)
val Color_DarkSurfaceBright = Color(0xFF343C3B)
val Color_DarkSurfaceDim = Color(0xFF0E1514)
